### ISSUE TITLE
heroku環境で画像が表示されない

### ISSUE THREAD

**Issue by smison** [smison/chiraura.pics#10]
heroku環境で画像を投稿すると一見successしたように見えるが、画像自体はnot foundとなる。

**Comment by smison** [comment]
どうやらherokuの仕様上静的ファイルは保存できない模様。
https://github.com/massakai/rails-sandbox/issues/5

外部DB上に画像を保存するのがよいか。

**Comment by smison** [comment]
- Cloudinary + Carrierwave + Heroku + Railsでの画像を手軽に利用する方法
 - http://qiita.com/GenTamura84/items/38cf899827bba050a21c

```
現在、Herokuで利用されているCedarスタックは、画像の保存はできるものの、Herokuを再起動したり、Pushすると保存していた画像が消えてしまいます。
そのため、Herokuのアプリケーション内で画像を保存するためには外部のストレージが必須です。
```

**Comment by smison** [comment]
Cloudinaryのフリープランで十分そう。

**Comment by smison** [comment]
CloudinaryはCarrierWave推奨らしい。
今使っているpaperclipだと色々問題が起きそう…。

**Comment by smison** [comment]
paperclip使い続けるならCloudinaryよりS3使うのがよさげ。
http://wine4u.seesaa.net/article/170193214.html

**Comment by smison** [comment]
当面はvps上にDB置くのでもよいか。
ただvpsでも ```-e production``` だと画像が表示されないので修正が必要。

**Comment by smison** [comment]
画像の保存自体はされている模様。
```
x?? mqq system
x??     mqq pictures
x??         mqq photos
x??             mqq 000
x??                 mqq 000
x??                     mqq 001
x??                         tqq medium
x??                         x?? mqq data
x??                         tqq original
x??                         x?? mqq data
x??                         mqq thumb
x??                             mqq data
```
しかしこういうエラー。
```
F, [2015-02-14T22:27:05.065332 #19894] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/system/pictures/photos/000/000/001/medium/data"):
  actionpack (4.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.0.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.3) lib/active_support/tagged_logging.rb:67:in `block in tagged'
  activesupport (4.0.3) lib/active_support/tagged_logging.rb:25:in `tagged'
  activesupport (4.0.3) lib/active_support/tagged_logging.rb:67:in `tagged'
  railties (4.0.3) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.3) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.3) lib/rails/engine.rb:511:in `call'
  railties (4.0.3) lib/rails/application.rb:97:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /usr/local/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
  /usr/local/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
  /usr/local/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by smison** [comment]
と思ったけど解決策見つからず。仕方ないのでproduction環境でもprecompileのオプションはずして対処。
```
--- a/config/environments/production.rb
+++ b/config/environments/production.rb
@@ -20,7 +20,7 @@ UragamiMe::Application.configure do
   # config.action_dispatch.rack_cache = true

   # Disable Rails's static asset server (Apache or nginx will already do this).
-  config.serve_static_assets = false
+  config.serve_static_assets = true
```

**Comment by smison** [comment]
上記のように ```config.serve_static_assets = true``` したあとで ```$ git push heroku master``` したらheroku上でも投稿した画像が見えるようになった。。。
