### ISSUE TITLE
heroku環境で.keyファイルがnot foundになり起動できない

### ISSUE THREAD

**Issue by smison** [smison/chiraura.pics#50]
.keyファイルはcommitしてないから当たり前なんだけど、
環境変数に値を入れるなどして対処する必要がある。

HerokuとGitHubの両方にプッシュする時の秘密にしたい値の扱い http://blog.ruedap.com/2011/01/30/git-heroku-github-push-secret-value

**Comment by smison** [comment]
鍵情報は環境変数に持たせるようにした( https://github.com/smison/chiraura.pics/commit/fdfdd76aa22dadf53d360125496a7abebf053a7c )ので、

下記でOK。
```
$ heroku config:add TWITTER_API_KEY=${TWITTER_API_KEY} --app=chiraura-pics
$ heroku config:add TWITTER_API_SECRET=${TWITTER_API_SECRET} --app=chiraura-pics
```

起動はしたがまだ認証後にコケる。callback urlが違うから？

**Comment by smison** [comment]
```
2015-02-22T03:48:20.181822+00:00 app[web.1]: F, [2015-02-22T03:48:20.181531 #3] FATAL -- :
2015-02-22T03:48:20.181825+00:00 app[web.1]: OAuth::Unauthorized (401 Authorization Required):
2015-02-22T03:48:20.181820+00:00 app[web.1]: I, [2015-02-22T03:48:19.952299 #3]  INFO -- omniauth: (twitter) Request phase initiated.
2015-02-22T03:48:20.181829+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:136:in `get_request_token'
2015-02-22T03:48:20.181818+00:00 app[web.1]: I, [2015-02-22T03:48:19.951820 #3]  INFO -- : Started GET "/users/auth/twitter" for 124.147.77.90 at 2015-02-22 03:48:19 +0000
2015-02-22T03:48:20.181827+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:216:in `token_request'
2015-02-22T03:48:20.181832+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/omniauth-oauth-1.0.1/lib/omniauth/strategies/oauth.rb:29:in `request_phase'
2015-02-22T03:48:20.181834+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/omniauth-twitter-1.0.1/lib/omniauth/strategies/twitter.rb:60:in `request_phase'
2015-02-22T03:48:20.181840+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
2015-02-22T03:48:20.181836+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:215:in `request_call'
2015-02-22T03:48:20.181838+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:183:in `call!'
2015-02-22T03:48:20.181843+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
2015-02-22T03:48:20.181846+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
2015-02-22T03:48:20.181845+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
2015-02-22T03:48:20.181848+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
2015-02-22T03:48:20.181849+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
2015-02-22T03:48:20.181851+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
```

**Comment by smison** [comment]
- TwitterのOAuthでrequest tokenを取得しようとして401 Unauthorizedがでるときの原因と対処法3つ
 - http://d.hatena.ne.jp/yayugu/20110813/1313220348

**Comment by smison** [comment]
解決済み
