### ISSUE TITLE
herokuにpushする際のGemfileに関する編集

### ISSUE THREAD

**Issue by smison** [smison/chiraura.pics#8]
めも

**Comment by smison** [comment]
remote:        rake aborted!
remote:        fatal: HandleScope::HandleScope: Entering the V8 API without proper locking in place

**Comment by smison** [comment]
```
remote: -----> Writing config/database.yml to read from DATABASE_URL
remote:        Could not detect rake tasks
remote:        ensure you can run `$ bundle exec rake -P` against your app with no environment variables present
remote:        and using the production group of your Gemfile.
remote:        This may be intentional, if you expected rake tasks to be run
remote:        cancel the build (CTRL+C) and fix the error then commit the fix:
remote:        rake aborted!
remote:        fatal: HandleScope::HandleScope: Entering the V8 API without proper locking in place
```

このへん？
- http://syonx.hatenablog.com/entry/2014/04/19/013414
- http://stackoverflow.com/questions/12379530/heroku-what-does-writing-config-database-yml-to-read-from-database-url-mean

**Comment by smison** [comment]
わかりやすい

- HerokuでRuby on Railsを立ち上げてみる(Windows)
 - http://tkoyama1988.hatenablog.com/entry/2013/12/13/072150

**Comment by smison** [comment]
$ heroku create chiraura-pics --stack cedar

でcreateしてもエラー内容は変わらず

**Comment by smison** [comment]
However heroku discouraged the use of therubyracer gems it's hard to remove this from existing projects without compromise the application.
http://www.kacode.com/v1680725-.html

therubyracerはheroku非推奨の模様

**Comment by smison** [comment]
Gemfile内のtherubyracerに関する記述を

proup :assets do
  gem 'therubyracer', :platforms => :ruby 
end

とすることでこのエラーは取れた。
参考: http://www.kacode.com/v1680725-.html

**Comment by smison** [comment]
まだ

We're sorry, but something went wrong.

なので、localで動かしてエラーの詳細を見る。
$ rails s -e production -p 8080

F, [2015-02-14T20:49:46.252441 #18186] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  actionpack (4.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.0.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'

こういうエラーが出てる

**Comment by smison** [comment]
ちがった。問題だったのはこっち。

I, [2015-02-14T20:58:52.994040 #18228]  INFO -- : Completed 500 Internal Server Error in 4ms
F, [2015-02-14T20:58:52.996760 #18228] FATAL -- :
ActionView::Template::Error (SQLite3::SQLException: no such table: pictures: SELECT "pictures".* FROM "pictures"):
    4: </div>
    5: <table class="table table-striped">
    6:   <tbody>
    7:     <% @pictures.each_with_index do |picture, index| %>
    8:       <% if index % 5 == 0 %>
    9:         <div class="row">
   10:         <div class="span1"></div>
  app/views/pictures/index.html.erb:7:in `_app_views_pictures_index_html_erb___2676233827344819100_70024544132760

本番用のDBがつくられていなかっただけなので、下記で解消。

$ rake db:migrate RAILS_ENV=production

**Comment by smison** [comment]
$ heroku run rake db:migrate

したらherokuでも動いた。つまり、
1. therubyracerが悪さしてた
2. dbつくられてなかった
という顛末。

**Comment by smison** [comment]
herokuで動作させるためにやらなきゃならないGemfileの編集は、下記の内容でよさそう。
https://github.com/smison/chiraura.pics/commit/e752c34d966c0384222491f9c1ef35534f50ba58
